package pl.virtual.api.gui;

import org.bukkit.entity.*;

import org.bukkit.*;
import org.bukkit.enchantments.Enchantment;

import pl.virtual.api.data.base.user.*;
import pl.virtual.api.managers.*;
import pl.virtual.api.utils.*;
import org.bukkit.inventory.*;

public class KitGui
{
    public static InventoryView show(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 27, ChatUtil.fixColor("&4&lZestawy"));
        final User u = UserManager.getUser(p);
        final ItemBuilder KitVip = new ItemBuilder(Material.IRON_HELMET).setTitle(ChatUtil.fixColor("&6&lKit VIP")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &6Status: " + (u.isKitVip() ? ("&cNiedostepny &8(&c" + DataUtil.secondsToString(u.getKit_vip()) + "&8)") : "&aDostepny"))).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &cKliknij aby sprawdzic kita"));
        final ItemBuilder KitStart = new ItemBuilder(Material.LEATHER_HELMET).setTitle(ChatUtil.fixColor("&6&lKit START")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &6Status: " + (u.isKitStart() ? ("&cNiedostepny &8(&c" + DataUtil.secondsToString(u.getKit_start()) + "&8)") : "&aDostepny"))).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &cKliknij aby sprawdzic kita"));
        final ItemBuilder KitSvip = new ItemBuilder(Material.GOLDEN_HELMET).setTitle(ChatUtil.fixColor("&6&lKit SVIP")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &6Status: " + (u.isKitSvip() ? ("&cNiedostepny &8(&c" + DataUtil.secondsToString(u.getKit_svip()) + "&8)") : "&aDostepny"))).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &cKliknij aby sprawdzic kita"));
        final ItemBuilder Kitdr = new ItemBuilder(Material.DIAMOND_HELMET).setTitle(ChatUtil.fixColor("&6&lKit SPONSOR")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &6Status: " + (u.isKitSvip() ? ("&cNiedostepny &8(&c" + DataUtil.secondsToString(u.getKit_svip()) + "&8)") : "&aDostepny"))).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &cKliknij aby sprawdzic kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS_PANE).setTitle(ChatUtil.fixColor("&8#"));
        inv.setItem(0, air.build());
        inv.setItem(1, air.build());
        inv.setItem(2, air.build());
        inv.setItem(3, air.build());
        inv.setItem(4, air.build());
        inv.setItem(5, air.build());
        inv.setItem(6, air.build());
        inv.setItem(7, air.build());
        inv.setItem(8, air.build());
        inv.setItem(9, air.build());
        inv.setItem(10, KitStart.build());
        inv.setItem(11, air.build());
        inv.setItem(12, KitVip.build());
        inv.setItem(13, air.build());
        inv.setItem(14, KitSvip.build());
        inv.setItem(15, air.build());
        inv.setItem(16, Kitdr.build());
        inv.setItem(17, air.build());
        inv.setItem(18, air.build());
        inv.setItem(19, air.build());
        inv.setItem(20, air.build());
        inv.setItem(21, air.build());
        inv.setItem(22, air.build());
        inv.setItem(23, air.build());
        inv.setItem(24, air.build());
        inv.setItem(25, air.build());
        inv.setItem(26, air.build());
        return p.openInventory(inv);
    }
    
    public static InventoryView show1(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 54, ChatUtil.fixColor("&4&lKit Start"));
        final User u = UserManager.getUser(p);
        final ItemBuilder Kit = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cNacisnij zeby odebrac kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&8#"));
        final ItemBuilder i1 = new ItemBuilder(Material.IRON_PICKAXE);
        final ItemBuilder i2 = new ItemBuilder(Material.ENDER_CHEST);
        final ItemBuilder i3 = new ItemBuilder(Material.COOKED_BEEF, 64);
        final ItemBuilder i4 = new ItemBuilder(Material.OAK_WOOD, 48);
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(53, wroc.build());
        inv.setItem(52, Kit.build());
        inv.setItem(inv.getSize() - 36 - 9 - 9, i1.build());
        inv.setItem(inv.getSize() - 35 - 9 - 9, i2.build());
        inv.setItem(inv.getSize() - 34 - 9 - 9, i3.build());
        inv.setItem(inv.getSize() - 33 - 9 - 9, i4.build());
        return p.openInventory(inv);
    }
    
    public static InventoryView show2(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 54, ChatUtil.fixColor("&4&lKit VIP"));
        final User u = UserManager.getUser(p);
        final ItemBuilder Kit = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cNacisnij zeby odebrac kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&8#"));
        final ItemBuilder i1 = new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i2 = new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i3 = new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i4 = new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i6 = new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2);
        final ItemBuilder i5 = new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1);
        final ItemBuilder i7 = new ItemBuilder(Material.BOW).addEnchantment(Enchantment.ARROW_DAMAGE, 3).addEnchantment(Enchantment.ARROW_FIRE, 1).addEnchantment(Enchantment.DURABILITY, 3);
        final ItemBuilder kilof = new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3);
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE, 1);
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE, 12, (short)0);
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL, 3, (short)0);
        final ItemBuilder arrow = new ItemBuilder(Material.ARROW, 64);
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(53, wroc.build());
        inv.setItem(52, Kit.build());
        inv.setItem(inv.getSize() - 36 - 9 - 9, i1.build());
        inv.setItem(inv.getSize() - 35 - 9 - 9, i2.build());
        inv.setItem(inv.getSize() - 34 - 9 - 9, i3.build());
        inv.setItem(inv.getSize() - 33 - 9 - 9, i4.build());
        inv.setItem(inv.getSize() - 32 - 9 - 9, i5.build());
        inv.setItem(inv.getSize() - 31 - 9 - 9, i6.build());
        inv.setItem(inv.getSize() - 30 - 9 - 9, i7.build());
        inv.setItem(inv.getSize() - 27 - 9 - 9, kilof.build());
        inv.setItem(inv.getSize() - 26 - 9 - 9, kox.build());
        inv.setItem(inv.getSize() - 25 - 9 - 9, ref.build());
        inv.setItem(inv.getSize() - 24 - 9 - 9, ender.build());
        inv.setItem(inv.getSize() - 23 - 9 - 9, arrow.build());
        return p.openInventory(inv);
    }
    
    public static InventoryView show2iron(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 54, ChatUtil.fixColor("&4&lKit VIP"));
        final User u = UserManager.getUser(p);
        final ItemBuilder Kit = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cNacisnij zeby odebrac kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&8#"));
        final ItemBuilder i1 = new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i2 = new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i3 = new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i4 = new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i6 = new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2);
        final ItemBuilder i5 = new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1);
        final ItemBuilder i7 = new ItemBuilder(Material.BOW).addEnchantment(Enchantment.ARROW_DAMAGE, 3).addEnchantment(Enchantment.ARROW_FIRE, 1).addEnchantment(Enchantment.DURABILITY, 3);
        final ItemBuilder kilof = new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3);
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE, 1);
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE, 12);
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL, 3);
        final ItemBuilder arrow = new ItemBuilder(Material.ARROW, 64);
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(53, wroc.build());
        inv.setItem(52, Kit.build());
        inv.setItem(inv.getSize() - 36 - 9 - 9, i1.build());
        inv.setItem(inv.getSize() - 35 - 9 - 9, i2.build());
        inv.setItem(inv.getSize() - 34 - 9 - 9, i3.build());
        inv.setItem(inv.getSize() - 33 - 9 - 9, i4.build());
        inv.setItem(inv.getSize() - 32 - 9 - 9, i5.build());
        inv.setItem(inv.getSize() - 31 - 9 - 9, i6.build());
        inv.setItem(inv.getSize() - 30 - 9 - 9, i7.build());
        inv.setItem(inv.getSize() - 27 - 9 - 9, kilof.build());
        inv.setItem(inv.getSize() - 26 - 9 - 9, kox.build());
        inv.setItem(inv.getSize() - 25 - 9 - 9, ref.build());
        inv.setItem(inv.getSize() - 24 - 9 - 9, ender.build());
        inv.setItem(inv.getSize() - 23 - 9 - 9, arrow.build());
        return p.openInventory(inv);
    }
    
    public static InventoryView show3(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 54, ChatUtil.fixColor("&4&lKit SVIP"));
        final User u = UserManager.getUser(p);
        final ItemBuilder Kit = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cNacisnij zeby odebrac kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&8#"));
        final ItemBuilder i1 = new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i2 = new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i3 = new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i4 = new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i6 = new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2);
        final ItemBuilder i7 = new ItemBuilder(Material.BOW).addEnchantment(Enchantment.ARROW_DAMAGE, 3).addEnchantment(Enchantment.ARROW_FIRE, 1).addEnchantment(Enchantment.DURABILITY, 3);
        final ItemBuilder i5 = new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1);
        final ItemBuilder kilof = new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3);
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE, 2);
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE, 24);
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL, 6);
        final ItemBuilder arrow = new ItemBuilder(Material.ARROW, 64);
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(53, wroc.build());
        inv.setItem(52, Kit.build());
        inv.setItem(inv.getSize() - 36 - 9 - 9, i1.build());
        inv.setItem(inv.getSize() - 35 - 9 - 9, i2.build());
        inv.setItem(inv.getSize() - 34 - 9 - 9, i3.build());
        inv.setItem(inv.getSize() - 33 - 9 - 9, i4.build());
        inv.setItem(inv.getSize() - 32 - 9 - 9, i5.build());
        inv.setItem(inv.getSize() - 31 - 9 - 9, i6.build());
        inv.setItem(inv.getSize() - 30 - 9 - 9, i7.build());
        inv.setItem(inv.getSize() - 27 - 9 - 9, i1.build());
        inv.setItem(inv.getSize() - 26 - 9 - 9, i2.build());
        inv.setItem(inv.getSize() - 25 - 9 - 9, i3.build());
        inv.setItem(inv.getSize() - 24 - 9 - 9, i4.build());
        inv.setItem(inv.getSize() - 23 - 9 - 9, i5.build());
        inv.setItem(inv.getSize() - 22 - 9 - 9, i6.build());
        inv.setItem(inv.getSize() - 18 - 9 - 9, kilof.build());
        inv.setItem(inv.getSize() - 17 - 9 - 9, kilof.build());
        inv.setItem(inv.getSize() - 16 - 9 - 9, kox.build());
        inv.setItem(inv.getSize() - 15 - 9 - 9, ref.build());
        inv.setItem(inv.getSize() - 14 - 9 - 9, ender.build());
        inv.setItem(inv.getSize() - 13 - 9 - 9, arrow.build());
        return p.openInventory(inv);
    }
    
    public static InventoryView show3iron(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 54, ChatUtil.fixColor("&4&lKit SVIP"));
        final User u = UserManager.getUser(p);
        final ItemBuilder Kit = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cNacisnij zeby odebrac kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&8#"));
        final ItemBuilder i1 = new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i2 = new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i3 = new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i4 = new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i6 = new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2);
        final ItemBuilder i7 = new ItemBuilder(Material.BOW).addEnchantment(Enchantment.ARROW_DAMAGE, 3).addEnchantment(Enchantment.ARROW_FIRE, 1).addEnchantment(Enchantment.DURABILITY, 3);
        final ItemBuilder i5 = new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1);
        final ItemBuilder kilof = new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3);
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE, 2);
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE, 24);
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL, 6);
        final ItemBuilder arrow = new ItemBuilder(Material.ARROW, 64);
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(53, wroc.build());
        inv.setItem(52, Kit.build());
        inv.setItem(inv.getSize() - 36 - 9 - 9, i1.build());
        inv.setItem(inv.getSize() - 35 - 9 - 9, i2.build());
        inv.setItem(inv.getSize() - 34 - 9 - 9, i3.build());
        inv.setItem(inv.getSize() - 33 - 9 - 9, i4.build());
        inv.setItem(inv.getSize() - 32 - 9 - 9, i5.build());
        inv.setItem(inv.getSize() - 31 - 9 - 9, i6.build());
        inv.setItem(inv.getSize() - 30 - 9 - 9, i7.build());
        inv.setItem(inv.getSize() - 27 - 9 - 9, i1.build());
        inv.setItem(inv.getSize() - 26 - 9 - 9, i2.build());
        inv.setItem(inv.getSize() - 25 - 9 - 9, i3.build());
        inv.setItem(inv.getSize() - 24 - 9 - 9, i4.build());
        inv.setItem(inv.getSize() - 23 - 9 - 9, i5.build());
        inv.setItem(inv.getSize() - 22 - 9 - 9, i6.build());
        inv.setItem(inv.getSize() - 18 - 9 - 9, kilof.build());
        inv.setItem(inv.getSize() - 17 - 9 - 9, kilof.build());
        inv.setItem(inv.getSize() - 16 - 9 - 9, kox.build());
        inv.setItem(inv.getSize() - 15 - 9 - 9, ref.build());
        inv.setItem(inv.getSize() - 14 - 9 - 9, ender.build());
        inv.setItem(inv.getSize() - 13 - 9 - 9, arrow.build());
        return p.openInventory(inv);
    }
    
    public static InventoryView show4(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 54, ChatUtil.fixColor("&4&lKit SPONSOR"));
        final User u = UserManager.getUser(p);
        final ItemBuilder Kit = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cNacisnij zeby odebrac kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&8#"));
        final ItemBuilder i1 = new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i2 = new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i3 = new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i4 = new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i6 = new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2);
        final ItemBuilder i7 = new ItemBuilder(Material.BOW).addEnchantment(Enchantment.ARROW_DAMAGE, 3).addEnchantment(Enchantment.ARROW_FIRE, 1).addEnchantment(Enchantment.DURABILITY, 3);
        final ItemBuilder i5 = new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1);
        final ItemBuilder kilof = new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3);
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE, 3);
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE, 36);
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL, 9);
        final ItemBuilder arrow = new ItemBuilder(Material.ARROW, 64);
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(53, wroc.build());
        inv.setItem(52, Kit.build());
        inv.setItem(inv.getSize() - 18 - 9, i7.build());
        inv.setItem(inv.getSize() - 17 - 9, i7.build());
        inv.setItem(inv.getSize() - 45 - 9, i1.build());
        inv.setItem(inv.getSize() - 44 - 9, i2.build());
        inv.setItem(inv.getSize() - 43 - 9, i3.build());
        inv.setItem(inv.getSize() - 42 - 9, i4.build());
        inv.setItem(inv.getSize() - 41 - 9, kilof.build());
        inv.setItem(inv.getSize() - 40 - 9, i5.build());
        inv.setItem(inv.getSize() - 39 - 9, i6.build());
        inv.setItem(inv.getSize() - 38 - 9, kox.build());
        inv.setItem(inv.getSize() - 36 - 9, i1.build());
        inv.setItem(inv.getSize() - 35 - 9, i2.build());
        inv.setItem(inv.getSize() - 34 - 9, i3.build());
        inv.setItem(inv.getSize() - 33 - 9, i4.build());
        inv.setItem(inv.getSize() - 32 - 9, kilof.build());
        inv.setItem(inv.getSize() - 31 - 9, i5.build());
        inv.setItem(inv.getSize() - 30 - 9, i6.build());
        inv.setItem(inv.getSize() - 29 - 9, ref.build());
        inv.setItem(inv.getSize() - 27 - 9, i1.build());
        inv.setItem(inv.getSize() - 26 - 9, i2.build());
        inv.setItem(inv.getSize() - 25 - 9, i3.build());
        inv.setItem(inv.getSize() - 24 - 9, i4.build());
        inv.setItem(inv.getSize() - 23 - 9, kilof.build());
        inv.setItem(inv.getSize() - 22 - 9, i5.build());
        inv.setItem(inv.getSize() - 21 - 9, i6.build());
        inv.setItem(inv.getSize() - 20 - 9, ender.build());
        inv.setItem(inv.getSize() - 16 - 9, arrow.build());
        return p.openInventory(inv);
    }
    
    public static InventoryView show4iron(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 54, ChatUtil.fixColor("&4&lKit SPONSOR"));
        final User u = UserManager.getUser(p);
        final ItemBuilder Kit = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cNacisnij zeby odebrac kita"));
        final ItemBuilder air = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&8#"));
        final ItemBuilder i1 = new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i2 = new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i3 = new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i4 = new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2);
        final ItemBuilder i6 = new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2);
        final ItemBuilder i7 = new ItemBuilder(Material.BOW).addEnchantment(Enchantment.ARROW_DAMAGE, 3).addEnchantment(Enchantment.ARROW_FIRE, 1).addEnchantment(Enchantment.DURABILITY, 3);
        final ItemBuilder i5 = new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1);
        final ItemBuilder kilof = new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3);
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE, 3);
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE, 36);
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL, 9);
        final ItemBuilder arrow = new ItemBuilder(Material.ARROW, 64);
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(53, wroc.build());
        inv.setItem(52, Kit.build());
        inv.setItem(inv.getSize() - 18 - 9, i7.build());
        inv.setItem(inv.getSize() - 17 - 9, i7.build());
        inv.setItem(inv.getSize() - 45 - 9, i1.build());
        inv.setItem(inv.getSize() - 44 - 9, i2.build());
        inv.setItem(inv.getSize() - 43 - 9, i3.build());
        inv.setItem(inv.getSize() - 42 - 9, i4.build());
        inv.setItem(inv.getSize() - 41 - 9, kilof.build());
        inv.setItem(inv.getSize() - 40 - 9, i5.build());
        inv.setItem(inv.getSize() - 39 - 9, i6.build());
        inv.setItem(inv.getSize() - 38 - 9, kox.build());
        inv.setItem(inv.getSize() - 36 - 9, i1.build());
        inv.setItem(inv.getSize() - 35 - 9, i2.build());
        inv.setItem(inv.getSize() - 34 - 9, i3.build());
        inv.setItem(inv.getSize() - 33 - 9, i4.build());
        inv.setItem(inv.getSize() - 32 - 9, kilof.build());
        inv.setItem(inv.getSize() - 31 - 9, i5.build());
        inv.setItem(inv.getSize() - 30 - 9, i6.build());
        inv.setItem(inv.getSize() - 29 - 9, ref.build());
        inv.setItem(inv.getSize() - 27 - 9, i1.build());
        inv.setItem(inv.getSize() - 26 - 9, i2.build());
        inv.setItem(inv.getSize() - 25 - 9, i3.build());
        inv.setItem(inv.getSize() - 24 - 9, i4.build());
        inv.setItem(inv.getSize() - 23 - 9, kilof.build());
        inv.setItem(inv.getSize() - 22 - 9, i5.build());
        inv.setItem(inv.getSize() - 21 - 9, i6.build());
        inv.setItem(inv.getSize() - 20 - 9, ender.build());
        inv.setItem(inv.getSize() - 16 - 9, arrow.build());
        return p.openInventory(inv);
    }
}
