package pl.virtual.api.gui;

import org.bukkit.entity.*;
import org.bukkit.*;

import pl.virtual.api.data.base.user.*;
import pl.virtual.api.managers.*;
import pl.virtual.api.utils.*;

import org.bukkit.inventory.*;
import org.bukkit.enchantments.*;

public class SklepGui
{
    public static void show(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lSklep"));
        final User u = UserManager.getUser(p);
        final ItemBuilder ch1 = new ItemBuilder(Material.RED_BANNER).setTitle(ChatUtil.fixColor("&c&LSPRZEDAJ")).addLore(ChatUtil.fixColor("&8� &7Kliknij aby przejsc dalej"));
        final ItemBuilder ch2 = new ItemBuilder(Material.LIME_BANNER).setTitle(ChatUtil.fixColor("&a&LKUP")).addLore(ChatUtil.fixColor("&8� &7Kliknij aby przejsc dalej"));
        final ItemBuilder ch3 = new ItemBuilder(Material.YELLOW_BANNER).setTitle(ChatUtil.fixColor("&6&lBOOSTY")).addLore(ChatUtil.fixColor("&8� &7Kliknij aby przejsc dalej"));
        final ItemBuilder szkl = new ItemBuilder(Material.GRAY_STAINED_GLASS_PANE).setTitle(ChatUtil.fixColor("&8\u2022"));
        inv.setItem(inv.getSize() - 45, szkl.build());
        inv.setItem(inv.getSize() - 44, szkl.build());
        inv.setItem(inv.getSize() - 43, szkl.build());
        inv.setItem(inv.getSize() - 42, szkl.build());
        inv.setItem(inv.getSize() - 41, szkl.build());
        inv.setItem(inv.getSize() - 40, szkl.build());
        inv.setItem(inv.getSize() - 39, szkl.build());
        inv.setItem(inv.getSize() - 38, szkl.build());
        inv.setItem(inv.getSize() - 37, szkl.build());
        inv.setItem(inv.getSize() - 36, szkl.build());
        inv.setItem(inv.getSize() - 35, szkl.build());
        inv.setItem(inv.getSize() - 34, ch1.build());
        inv.setItem(inv.getSize() - 33, szkl.build());
        inv.setItem(inv.getSize() - 32, szkl.build());
        inv.setItem(inv.getSize() - 31, szkl.build());
        inv.setItem(inv.getSize() - 30, ch2.build());
        inv.setItem(inv.getSize() - 29, szkl.build());
        inv.setItem(inv.getSize() - 28, szkl.build());
        inv.setItem(inv.getSize() - 27, szkl.build());
        inv.setItem(inv.getSize() - 26, szkl.build());
        inv.setItem(inv.getSize() - 25, szkl.build());
        inv.setItem(inv.getSize() - 24, szkl.build());
        inv.setItem(inv.getSize() - 23, szkl.build());
        inv.setItem(inv.getSize() - 22, szkl.build());
        inv.setItem(inv.getSize() - 21, szkl.build());
        inv.setItem(inv.getSize() - 20, szkl.build());
        inv.setItem(inv.getSize() - 19, szkl.build());
        inv.setItem(inv.getSize() - 18, szkl.build());
        inv.setItem(inv.getSize() - 17, szkl.build());
        inv.setItem(inv.getSize() - 16, szkl.build());
        inv.setItem(inv.getSize() - 15, szkl.build());
        inv.setItem(inv.getSize() - 14, ch3.build());
        inv.setItem(inv.getSize() - 13, szkl.build());
        inv.setItem(inv.getSize() - 12, szkl.build());
        inv.setItem(inv.getSize() - 11, szkl.build());
        inv.setItem(inv.getSize() - 10, szkl.build());
        inv.setItem(inv.getSize() - 9, szkl.build());
        inv.setItem(inv.getSize() - 8, szkl.build());
        inv.setItem(inv.getSize() - 7, szkl.build());
        inv.setItem(inv.getSize() - 6, szkl.build());
        inv.setItem(inv.getSize() - 5, szkl.build());
        inv.setItem(inv.getSize() - 4, szkl.build());
        inv.setItem(inv.getSize() - 3, szkl.build());
        inv.setItem(inv.getSize() - 2, szkl.build());
        inv.setItem(inv.getSize() - 1, szkl.build());
        p.openInventory(inv);
    }   
    
    public static void showguild(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lSklep"));
        final User u = UserManager.getUser(p);
        final ItemBuilder ch1 = new ItemBuilder(Material.RED_BANNER).setTitle(ChatUtil.fixColor("&c&LSPRZEDAJ")).addLore(ChatUtil.fixColor("&8� &7Kliknij aby przejsc dalej"));
        final ItemBuilder ch2 = new ItemBuilder(Material.LIME_BANNER).setTitle(ChatUtil.fixColor("&a&LKUP")).addLore(ChatUtil.fixColor("&8� &7Kliknij aby przejsc dalej"));
        final ItemBuilder ch3 = new ItemBuilder(Material.YELLOW_BANNER).setTitle(ChatUtil.fixColor("&6&lBOOSTY")).addLore(ChatUtil.fixColor("&8� &7Kliknij aby przejsc dalej"));
        final ItemBuilder szkl = new ItemBuilder(Material.GRAY_STAINED_GLASS_PANE).setTitle(ChatUtil.fixColor("&8\u2022"));
        final ItemBuilder ch4 = new ItemBuilder(Material.BLUE_BANNER).setTitle(ChatUtil.fixColor("&6&lGILDIA")).addLore(ChatUtil.fixColor("&8� &7Kliknij aby przejsc dalej"));
        inv.setItem(inv.getSize() - 45, szkl.build());
        inv.setItem(inv.getSize() - 44, szkl.build());
        inv.setItem(inv.getSize() - 43, szkl.build());
        inv.setItem(inv.getSize() - 42, szkl.build());
        inv.setItem(inv.getSize() - 41, szkl.build());
        inv.setItem(inv.getSize() - 40, szkl.build());
        inv.setItem(inv.getSize() - 39, szkl.build());
        inv.setItem(inv.getSize() - 38, szkl.build());
        inv.setItem(inv.getSize() - 37, szkl.build());
        inv.setItem(inv.getSize() - 36, szkl.build());
        inv.setItem(inv.getSize() - 35, szkl.build());
        inv.setItem(inv.getSize() - 34, ch1.build());
        inv.setItem(inv.getSize() - 33, szkl.build());
        inv.setItem(inv.getSize() - 32, ch4.build());
        inv.setItem(inv.getSize() - 31, szkl.build());
        inv.setItem(inv.getSize() - 30, ch2.build());
        inv.setItem(inv.getSize() - 29, szkl.build());
        inv.setItem(inv.getSize() - 28, szkl.build());
        inv.setItem(inv.getSize() - 27, szkl.build());
        inv.setItem(inv.getSize() - 26, szkl.build());
        inv.setItem(inv.getSize() - 25, szkl.build());
        inv.setItem(inv.getSize() - 24, szkl.build());
        inv.setItem(inv.getSize() - 23, szkl.build());
        inv.setItem(inv.getSize() - 22, szkl.build());
        inv.setItem(inv.getSize() - 21, szkl.build());
        inv.setItem(inv.getSize() - 20, szkl.build());
        inv.setItem(inv.getSize() - 19, szkl.build());
        inv.setItem(inv.getSize() - 18, szkl.build());
        inv.setItem(inv.getSize() - 17, szkl.build());
        inv.setItem(inv.getSize() - 16, szkl.build());
        inv.setItem(inv.getSize() - 15, szkl.build());
        inv.setItem(inv.getSize() - 14, ch3.build());
        inv.setItem(inv.getSize() - 13, szkl.build());
        inv.setItem(inv.getSize() - 12, szkl.build());
        inv.setItem(inv.getSize() - 11, szkl.build());
        inv.setItem(inv.getSize() - 10, szkl.build());
        inv.setItem(inv.getSize() - 9, szkl.build());
        inv.setItem(inv.getSize() - 8, szkl.build());
        inv.setItem(inv.getSize() - 7, szkl.build());
        inv.setItem(inv.getSize() - 6, szkl.build());
        inv.setItem(inv.getSize() - 5, szkl.build());
        inv.setItem(inv.getSize() - 4, szkl.build());
        inv.setItem(inv.getSize() - 3, szkl.build());
        inv.setItem(inv.getSize() - 2, szkl.build());
        inv.setItem(inv.getSize() - 1, szkl.build());
        p.openInventory(inv);
    }   
    
    public static InventoryView show1(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lSklep SELL"));
        final ItemBuilder bibl = new ItemBuilder(Material.BOOKSHELF).setTitle(ChatUtil.fixColor("&4&lBIBLIOTECZKA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &625 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c10")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder cobble = new ItemBuilder(Material.COBBLESTONE).setTitle(ChatUtil.fixColor("&4&lBRUK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &65 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder tnt = new ItemBuilder(Material.TNT).setTitle(ChatUtil.fixColor("&4&lTNT")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &690 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c32")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder slime = new ItemBuilder(Material.SLIME_BALL).setTitle(ChatUtil.fixColor("&4&lKULA SZLAMU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &620 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder diamond = new ItemBuilder(Material.DIAMOND).setTitle(ChatUtil.fixColor("&4&lDIAMENTY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &630 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder emerald = new ItemBuilder(Material.EMERALD).setTitle(ChatUtil.fixColor("&4&lSZMARAGDY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &640 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder iron = new ItemBuilder(Material.IRON_INGOT).setTitle(ChatUtil.fixColor("&4&lSZTABKI ZELAZA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &620 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder gold = new ItemBuilder(Material.GOLD_INGOT).setTitle(ChatUtil.fixColor("&4&lSZTABKI ZLOTA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &650 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder pearl = new ItemBuilder(Material.ENDER_PEARL).setTitle(ChatUtil.fixColor("&4&lPERLY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &670 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE).setTitle(ChatUtil.fixColor("&4&lKOX")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &655 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE).setTitle(ChatUtil.fixColor("&4&lREFIL")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &615 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder beac = new ItemBuilder(Material.BEACON).setTitle(ChatUtil.fixColor("&4&lBEACON")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &625.000 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder cactus = new ItemBuilder(Material.CACTUS).setTitle(ChatUtil.fixColor("&4&lKAKTUS")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6120 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder whe = new ItemBuilder(Material.WHEAT).setTitle(ChatUtil.fixColor("&4&lSIANO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder coco = new ItemBuilder(Material.COCOA_BEANS).setTitle(ChatUtil.fixColor("&4&lKAKAOWIEC")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6120 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder melon = new ItemBuilder(Material.MELON).setTitle(ChatUtil.fixColor("&4&lMELON")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder obs = new ItemBuilder(Material.OBSIDIAN).setTitle(ChatUtil.fixColor("&4&lOBSYDIAN")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &660 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        final ItemBuilder sellall = new ItemBuilder(Material.PAPER).setTitle(ChatUtil.fixColor("&cSprzedaj wszystko co mozesz"));
        final ItemBuilder red = new ItemBuilder(Material.REDSTONE).setTitle(ChatUtil.fixColor("&4&lREDSTONE")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &65 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        final ItemBuilder col = new ItemBuilder(Material.COAL).setTitle(ChatUtil.fixColor("&4&lWEGIEL")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &625 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby sprzedac"));
        inv.setItem(inv.getSize() - 45, diamond.build());
        inv.setItem(inv.getSize() - 44, emerald.build());
        inv.setItem(inv.getSize() - 43, iron.build());
        inv.setItem(inv.getSize() - 42, gold.build());
        inv.setItem(inv.getSize() - 41, red.build());
        inv.setItem(inv.getSize() - 40, col.build());
        inv.setItem(inv.getSize() - 36, bibl.build());
        inv.setItem(inv.getSize() - 35, slime.build());
        inv.setItem(inv.getSize() - 34, obs.build());
        inv.setItem(inv.getSize() - 33, cobble.build());
        inv.setItem(inv.getSize() - 32, tnt.build());
        inv.setItem(inv.getSize() - 27, pearl.build());
        inv.setItem(inv.getSize() - 26, kox.build());
        inv.setItem(inv.getSize() - 25, ref.build());
        inv.setItem(inv.getSize() - 24, beac.build());
        inv.setItem(inv.getSize() - 18, cactus.build());
        inv.setItem(inv.getSize() - 17, whe.build());
        inv.setItem(inv.getSize() - 16, melon.build());
        inv.setItem(inv.getSize() - 15, coco.build());
        inv.setItem(inv.getSize() - 2, sellall.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        return p.openInventory(inv);
    }
    
    public static void show2(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 36, ChatUtil.fixColor("&4&lSklep BUY"));
        final ItemBuilder next1 = new ItemBuilder(Material.DIAMOND_SWORD).setTitle(ChatUtil.fixColor("&4&lDZIAL WALKA")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next2 = new ItemBuilder(Material.RED_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lDZIAL SZKLO")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next3 = new ItemBuilder(Material.RED_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lDZIAL GLINA")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next4 = new ItemBuilder(Material.NETHERRACK).setTitle(ChatUtil.fixColor("&4&lDZIAL NETHER")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next5 = new ItemBuilder(Material.WHITE_WOOL).setTitle(ChatUtil.fixColor("&4&lDZIAL WELNA")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next10 = new ItemBuilder(Material.OAK_SAPLING).setTitle(ChatUtil.fixColor("&4&lDZIAL SADZONKI")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next9 = new ItemBuilder(Material.COOKED_BEEF).setTitle(ChatUtil.fixColor("&4&lDZIAL JEDZENIE")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next8 = new ItemBuilder(Material.REDSTONE_BLOCK).setTitle(ChatUtil.fixColor("&4&lDZIAL REDSTONE")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next6 = new ItemBuilder(Material.OAK_LOG).setTitle(ChatUtil.fixColor("&4&lDZIAL DREWNO")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next7 = new ItemBuilder(Material.STONE_BRICKS).setTitle(ChatUtil.fixColor("&4&lDZIAL BUDULEC")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder next11 = new ItemBuilder(Material.STRING).setTitle(ChatUtil.fixColor("&4&lDZIAL PRZYDATNE")).addLore("").addLore("�7Kliknij aby, przejsc dalej");
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 26, next1.build());
        inv.setItem(inv.getSize() - 25, next2.build());
        inv.setItem(inv.getSize() - 24, next3.build());
        inv.setItem(inv.getSize() - 23, next5.build());
        inv.setItem(inv.getSize() - 22, next6.build());
        inv.setItem(inv.getSize() - 21, next4.build());
        inv.setItem(inv.getSize() - 20, next7.build());
        inv.setItem(inv.getSize() - 15, next8.build());
        inv.setItem(inv.getSize() - 14, next9.build());
        inv.setItem(inv.getSize() - 13, next10.build());
        inv.setItem(inv.getSize() - 32, next11.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showwalka(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 36, ChatUtil.fixColor("&4&lDZIAL WALKA"));
        final ItemBuilder kilof6 = new ItemBuilder(Material.DIAMOND_PICKAXE).setTitle(ChatUtil.fixColor("&4&lKILOF 6/3/3")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.DIG_SPEED, 6).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).addLore(ChatUtil.fixColor("&8� &7Koszt: &650.000 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder kilof5 = new ItemBuilder(Material.DIAMOND_PICKAXE).setTitle(ChatUtil.fixColor("&4&lKILOF 5/3/3")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        final ItemBuilder nici = new ItemBuilder(Material.ARROW).setTitle(ChatUtil.fixColor("&4&lSTRZALY")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c32")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL).setTitle(ChatUtil.fixColor("&4&lPERLA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6800 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c2")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE).setTitle(ChatUtil.fixColor("&4&lKOX")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6300 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE).setTitle(ChatUtil.fixColor("&4&lREFIL")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &690 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder m2 = new ItemBuilder(Material.DIAMOND_SWORD).setTitle(ChatUtil.fixColor("&4&lMIECZ KNOCK")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.KNOCKBACK, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder m1 = new ItemBuilder(Material.DIAMOND_SWORD).setTitle(ChatUtil.fixColor("&4&lMIECZ 4/1")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.FIRE_ASPECT, 1).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set1 = new ItemBuilder(Material.DIAMOND_HELMET).setTitle(ChatUtil.fixColor("&4&lHELM")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set2 = new ItemBuilder(Material.DIAMOND_CHESTPLATE).setTitle(ChatUtil.fixColor("&4&lZBROJA")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set3 = new ItemBuilder(Material.DIAMOND_LEGGINGS).setTitle(ChatUtil.fixColor("&4&lSPODNIE")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set4 = new ItemBuilder(Material.DIAMOND_BOOTS).setTitle(ChatUtil.fixColor("&4&lBUTY")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        inv.setItem(inv.getSize() - 26, set1.build());
        inv.setItem(inv.getSize() - 25, set2.build());
        inv.setItem(inv.getSize() - 24, set3.build());
        inv.setItem(inv.getSize() - 23, set4.build());
        inv.setItem(inv.getSize() - 22, m1.build());
        inv.setItem(inv.getSize() - 21, m2.build());
        inv.setItem(inv.getSize() - 20, kilof5.build());
        inv.setItem(inv.getSize() - 17, kilof6.build());
        inv.setItem(inv.getSize() - 16, kox.build());
        inv.setItem(inv.getSize() - 15, ref.build());
        inv.setItem(inv.getSize() - 14, ender.build());
        inv.setItem(inv.getSize() - 13, nici.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showwalka2(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 36, ChatUtil.fixColor("&4&lDZIAL WALKA"));
        final ItemBuilder kilof6 = new ItemBuilder(Material.DIAMOND_PICKAXE).setTitle(ChatUtil.fixColor("&4&lKILOF 6/3/3")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.DIG_SPEED, 6).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).addLore(ChatUtil.fixColor("&8� &7Koszt: &650.000 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder kilof5 = new ItemBuilder(Material.DIAMOND_PICKAXE).setTitle(ChatUtil.fixColor("&4&lKILOF 5/3/3")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        final ItemBuilder beacon = new ItemBuilder(Material.BEACON).setTitle(ChatUtil.fixColor("&4&lBEACON")).addLore(ChatUtil.fixColor("&8� &7Koszt: &680.000 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder nici = new ItemBuilder(Material.ARROW).setTitle(ChatUtil.fixColor("&4&lSTRZALY")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c32")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder ender = new ItemBuilder(Material.ENDER_PEARL).setTitle(ChatUtil.fixColor("&4&lPERLA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6800 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c2")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder kox = new ItemBuilder(Material.ENCHANTED_GOLDEN_APPLE).setTitle(ChatUtil.fixColor("&4&lKOX")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &6300 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder ref = new ItemBuilder(Material.GOLDEN_APPLE).setTitle(ChatUtil.fixColor("&4&lREFIL")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Sprzedaj za: &690 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder m2 = new ItemBuilder(Material.IRON_SWORD).setTitle(ChatUtil.fixColor("&4&lMIECZ KNOCK")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.KNOCKBACK, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder m1 = new ItemBuilder(Material.IRON_SWORD).setTitle(ChatUtil.fixColor("&4&lMIECZ 3/1")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set1 = new ItemBuilder(Material.IRON_HELMET).setTitle(ChatUtil.fixColor("&4&lHELM")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set2 = new ItemBuilder(Material.IRON_CHESTPLATE).setTitle(ChatUtil.fixColor("&4&lZBROJA")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set3 = new ItemBuilder(Material.IRON_LEGGINGS).setTitle(ChatUtil.fixColor("&4&lSPODNIE")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder set4 = new ItemBuilder(Material.IRON_BOOTS).setTitle(ChatUtil.fixColor("&4&lBUTY")).addLore(ChatUtil.fixColor("")).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).addLore(ChatUtil.fixColor("&8� &7Koszt: &6160 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        inv.setItem(inv.getSize() - 26, set1.build());
        inv.setItem(inv.getSize() - 25, set2.build());
        inv.setItem(inv.getSize() - 24, set3.build());
        inv.setItem(inv.getSize() - 23, set4.build());
        inv.setItem(inv.getSize() - 22, m1.build());
        inv.setItem(inv.getSize() - 21, m2.build());
        inv.setItem(inv.getSize() - 20, kilof5.build());
        inv.setItem(inv.getSize() - 17, kilof6.build());
        inv.setItem(inv.getSize() - 16, kox.build());
        inv.setItem(inv.getSize() - 15, ref.build());
        inv.setItem(inv.getSize() - 14, ender.build());
        inv.setItem(inv.getSize() - 13, nici.build());
        inv.setItem(inv.getSize() - 12, beacon.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showszklo(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL SZKLO"));
        final ItemBuilder s1 = new ItemBuilder(Material.GLASS).setTitle(ChatUtil.fixColor("&4&lBIALE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.ORANGE_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lPOMARANCZOWE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.MAGENTA_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lKARMAZYNOWE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.LIGHT_BLUE_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lJASNONIEBIESKIE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.YELLOW_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lZOLTE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.LIME_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lLIMONKOWE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.PINK_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lROZOWE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lSZARE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.LIGHT_GRAY_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lJASNOSZARE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.CYAN_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lBLEKITNE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s11 = new ItemBuilder(Material.PURPLE_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lFIOLETOWE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s12 = new ItemBuilder(Material.BLUE_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lNIEBIESKIE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s13 = new ItemBuilder(Material.BROWN_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lBRAZOWE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s14 = new ItemBuilder(Material.GREEN_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lZIELONE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s15 = new ItemBuilder(Material.RED_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lCZERWONE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s16 = new ItemBuilder(Material.BLACK_STAINED_GLASS).setTitle(ChatUtil.fixColor("&4&lCZARNE SZKLO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 23, s11.build());
        inv.setItem(inv.getSize() - 22, s12.build());
        inv.setItem(inv.getSize() - 21, s13.build());
        inv.setItem(inv.getSize() - 20, s14.build());
        inv.setItem(inv.getSize() - 17, s15.build());
        inv.setItem(inv.getSize() - 16, s16.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showglina(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL SZKLO"));
        final ItemBuilder s1 = new ItemBuilder(Material.CLAY).setTitle(ChatUtil.fixColor("&4&lGLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.WHITE_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lBIALA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.ORANGE_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lPOMARANCZOWA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.MAGENTA_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lKARMAZYNOWA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.LIGHT_BLUE_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lJASNONIEBIESKA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.YELLOW_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lZOLTA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.LIME_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lJASNOZIELONA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &610 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.PINK_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lROZOWA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.GRAY_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lSZARA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.LIGHT_GRAY_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lJASNOSZARA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s11 = new ItemBuilder(Material.CYAN_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lBLEKITNA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s12 = new ItemBuilder(Material.PURPLE_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lFIOLETOWA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s13 = new ItemBuilder(Material.BLUE_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lNIEBIESKA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s14 = new ItemBuilder(Material.BROWN_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lBRAZOWA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s15 = new ItemBuilder(Material.GREEN_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lZIELONA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s16 = new ItemBuilder(Material.RED_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lCZERWONA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s17 = new ItemBuilder(Material.BLACK_TERRACOTTA).setTitle(ChatUtil.fixColor("&4&lCZARNA GLINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 23, s11.build());
        inv.setItem(inv.getSize() - 22, s12.build());
        inv.setItem(inv.getSize() - 21, s13.build());
        inv.setItem(inv.getSize() - 20, s14.build());
        inv.setItem(inv.getSize() - 17, s15.build());
        inv.setItem(inv.getSize() - 16, s16.build());
        inv.setItem(inv.getSize() - 15, s17.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showwelna(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL WELNA"));
        final ItemBuilder s1 = new ItemBuilder(Material.WHITE_WOOL).setTitle(ChatUtil.fixColor("&4&lWELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.ORANGE_WOOL).setTitle(ChatUtil.fixColor("&4&lPOMARANCZOWA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.MAGENTA_WOOL).setTitle(ChatUtil.fixColor("&4&lKARMAZYNOWA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.LIGHT_BLUE_WOOL).setTitle(ChatUtil.fixColor("&4&lJASNONIEBIESKA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.YELLOW_WOOL).setTitle(ChatUtil.fixColor("&4&lZOLTA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.LIME_WOOL).setTitle(ChatUtil.fixColor("&4&lJASNOZIELONA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.PINK_WOOL).setTitle(ChatUtil.fixColor("&4&lROZOWA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.GRAY_WOOL).setTitle(ChatUtil.fixColor("&4&lSZARA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.LIGHT_GRAY_WOOL).setTitle(ChatUtil.fixColor("&4&lJASNOSZARA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.CYAN_WOOL).setTitle(ChatUtil.fixColor("&4&lBLEKITNA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s11 = new ItemBuilder(Material.PURPLE_WOOL).setTitle(ChatUtil.fixColor("&4&lPURPUROWA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s12 = new ItemBuilder(Material.BLUE_WOOL).setTitle(ChatUtil.fixColor("&4&lNIEBIESKA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s13 = new ItemBuilder(Material.BROWN_WOOL).setTitle(ChatUtil.fixColor("&4&lBRAZOWA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s14 = new ItemBuilder(Material.GREEN_WOOL).setTitle(ChatUtil.fixColor("&4&lZIELONA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s15 = new ItemBuilder(Material.RED_WOOL).setTitle(ChatUtil.fixColor("&4&lCZERWONA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s16 = new ItemBuilder(Material.BLACK_WOOL).setTitle(ChatUtil.fixColor("&4&lCZARNA WELNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 23, s11.build());
        inv.setItem(inv.getSize() - 22, s12.build());
        inv.setItem(inv.getSize() - 21, s13.build());
        inv.setItem(inv.getSize() - 20, s14.build());
        inv.setItem(inv.getSize() - 17, s15.build());
        inv.setItem(inv.getSize() - 16, s16.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showdrzewo(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL DRZEWO"));
        final ItemBuilder s1 = new ItemBuilder(Material.OAK_LOG).setTitle(ChatUtil.fixColor("&4&lDRZEWO DEBOWE")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.SPRUCE_LOG).setTitle(ChatUtil.fixColor("&4&lDRZEWO SWIERKOWE")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.BIRCH_LOG).setTitle(ChatUtil.fixColor("&4&lDRZEWO BRZOZOWE")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.JUNGLE_LOG).setTitle(ChatUtil.fixColor("&4&lDRZEWO TROPIKALNE")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.ACACIA_LOG).setTitle(ChatUtil.fixColor("&4&lDRZEWO AKACJI")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.DARK_OAK_LOG).setTitle(ChatUtil.fixColor("&4&lDRZEWO CIEMNEGO DEBU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void shownether(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL NETHER"));
        final ItemBuilder s1 = new ItemBuilder(Material.SOUL_SAND).setTitle(ChatUtil.fixColor("&4&lPIASEK DUSZ")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.NETHERRACK).setTitle(ChatUtil.fixColor("&4&lNETHERRACK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.QUARTZ_STAIRS).setTitle(ChatUtil.fixColor("&4&lKWARCOWE SCHODY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.CHISELED_QUARTZ_BLOCK).setTitle(ChatUtil.fixColor("&4&lZEZBIONY BLOK KWARCU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.QUARTZ_BLOCK).setTitle(ChatUtil.fixColor("&4&lKWARCOWA KOLUMNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.QUARTZ_BLOCK).setTitle(ChatUtil.fixColor("&4&lBLOK KWARCU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.GLOWSTONE).setTitle(ChatUtil.fixColor("&4&lJASNOGLAS")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.NETHER_BRICK).setTitle(ChatUtil.fixColor("&4&lNETHEROWA CEGLA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.NETHER_BRICK_FENCE).setTitle(ChatUtil.fixColor("&4&lNETHEROWY PLOT")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.NETHER_BRICK_STAIRS).setTitle(ChatUtil.fixColor("&4&lNETHEROWE SCHODY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s11 = new ItemBuilder(Material.NETHER_QUARTZ_ORE).setTitle(ChatUtil.fixColor("&4&lRUDA KWARCU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s12 = new ItemBuilder(Material.LAVA_BUCKET).setTitle(ChatUtil.fixColor("&4&lWIADRO LAWY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 23, s11.build());
        inv.setItem(inv.getSize() - 22, s12.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showbudulec(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL BUDULEC"));
        final ItemBuilder s1 = new ItemBuilder(Material.STONE_BRICKS).setTitle(ChatUtil.fixColor("&4&lKAMIENNE CEGLY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.CHISELED_STONE_BRICKS).setTitle(ChatUtil.fixColor("&4&lRZEZBIONE KAMIENNE CEGLY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.CRACKED_STONE_BRICKS).setTitle(ChatUtil.fixColor("&4&lPEKNIETE KAMIENNE CEGLY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.MOSSY_STONE_BRICKS).setTitle(ChatUtil.fixColor("&4&lZAMSZONE KAMIENNE CEGLY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.MOSSY_COBBLESTONE).setTitle(ChatUtil.fixColor("&4&lZAMSZONY BRUK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.STONE).setTitle(ChatUtil.fixColor("&4&lKAMIEN")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.BRICK).setTitle(ChatUtil.fixColor("&4&lCEGLY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.GRAVEL).setTitle(ChatUtil.fixColor("&4&lZWIR")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.GRASS).setTitle(ChatUtil.fixColor("&4&lTRAWA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.COARSE_DIRT).setTitle(ChatUtil.fixColor("&4&lTWARDA ZIEMIA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s11 = new ItemBuilder(Material.PODZOL).setTitle(ChatUtil.fixColor("&4&lBIELICA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s12 = new ItemBuilder(Material.RED_SANDSTONE).setTitle(ChatUtil.fixColor("&4&lCZERWONY PIASKOWIEC")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s13 = new ItemBuilder(Material.SMOOTH_RED_SANDSTONE).setTitle(ChatUtil.fixColor("&4&lGLADKI CZERWONY PIASKOWIEC")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s14 = new ItemBuilder(Material.CHISELED_RED_SANDSTONE).setTitle(ChatUtil.fixColor("&4&lRZEZBIONY CZERWONY PIASKOWIEC")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s15 = new ItemBuilder(Material.LAPIS_BLOCK).setTitle(ChatUtil.fixColor("&4&lBLOK LAZURYTU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 23, s11.build());
        inv.setItem(inv.getSize() - 22, s12.build());
        inv.setItem(inv.getSize() - 21, s13.build());
        inv.setItem(inv.getSize() - 20, s14.build());
        inv.setItem(inv.getSize() - 17, s15.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showredstone(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL REDSTONE"));
        final ItemBuilder s1 = new ItemBuilder(Material.DISPENSER).setTitle(ChatUtil.fixColor("&4&lDOZOWNIK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.DROPPER).setTitle(ChatUtil.fixColor("&4&lPODAJNIK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.MOVING_PISTON).setTitle(ChatUtil.fixColor("&4&lLEPKI TLOK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.PISTON).setTitle(ChatUtil.fixColor("&4&lTLOK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.TNT).setTitle(ChatUtil.fixColor("&4&lTNT")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.REDSTONE_LAMP).setTitle(ChatUtil.fixColor("&4&lLAMPA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.REDSTONE_BLOCK).setTitle(ChatUtil.fixColor("&4&lBLOK REDSTONE")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.REPEATER).setTitle(ChatUtil.fixColor("&4&lPRZEKAZNIK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.COMPARATOR).setTitle(ChatUtil.fixColor("&4&lKOMPARATOR")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.DAYLIGHT_DETECTOR).setTitle(ChatUtil.fixColor("&4&lDETEKTOR")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showjedzenie(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL JEDZENIE"));
        final ItemBuilder s1 = new ItemBuilder(Material.APPLE).setTitle(ChatUtil.fixColor("&4&lJABLKO")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c8")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.MELON).setTitle(ChatUtil.fixColor("&4&lMELON")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.BAKED_POTATO).setTitle(ChatUtil.fixColor("&4&lPIECZONY ZIEMNIAK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.BREAD).setTitle(ChatUtil.fixColor("&4&lCHLEB")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.COOKED_COD).setTitle(ChatUtil.fixColor("&4&lPIECZONA RYBA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.COOKED_MUTTON).setTitle(ChatUtil.fixColor("&4&lPIECZONA BARANINA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.COOKED_BEEF).setTitle(ChatUtil.fixColor("&4&lBEBFSZTYK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.COOKED_PORKCHOP).setTitle(ChatUtil.fixColor("&4&lPIECZONY SCHAB")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.COOKED_RABBIT).setTitle(ChatUtil.fixColor("&4&lPIECZONY KROLIK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.COOKED_CHICKEN).setTitle(ChatUtil.fixColor("&4&lPIECZONY KURCZAK")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c64")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showsadzonki(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL SADZONKI"));
        final ItemBuilder s1 = new ItemBuilder(Material.OAK_SAPLING, 1).setTitle(ChatUtil.fixColor("&4&lSADZONKA DEBU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.SPRUCE_SAPLING, 1).setTitle(ChatUtil.fixColor("&4&lSADZONKA SWIERKU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.BIRCH_SAPLING, 1).setTitle(ChatUtil.fixColor("&4&lSADZONKA BRZOZY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.JUNGLE_SAPLING, 1).setTitle(ChatUtil.fixColor("&4&lSADZONKA TROPIKALNA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s5 = new ItemBuilder(Material.ACACIA_SAPLING, 1).setTitle(ChatUtil.fixColor("&4&lSADZONKA AKACJI")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s6 = new ItemBuilder(Material.DARK_OAK_SAPLING, 1).setTitle(ChatUtil.fixColor("&4&lSADZONKA CIEMNEGO DEBU")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s7 = new ItemBuilder(Material.COCOA_BEANS, 1).setTitle(ChatUtil.fixColor("&4&lZIARNA KAKAOWE")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s8 = new ItemBuilder(Material.CACTUS, 1).setTitle(ChatUtil.fixColor("&4&lKAKTUS")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s9 = new ItemBuilder(Material.WHEAT_SEEDS, 1).setTitle(ChatUtil.fixColor("&4&lNASIONA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s10 = new ItemBuilder(Material.MELON_SEEDS).setTitle(ChatUtil.fixColor("&4&lNASIONA MELONA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c4")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s2.build());
        inv.setItem(inv.getSize() - 33, s3.build());
        inv.setItem(inv.getSize() - 32, s4.build());
        inv.setItem(inv.getSize() - 31, s5.build());
        inv.setItem(inv.getSize() - 30, s6.build());
        inv.setItem(inv.getSize() - 29, s7.build());
        inv.setItem(inv.getSize() - 26, s8.build());
        inv.setItem(inv.getSize() - 25, s9.build());
        inv.setItem(inv.getSize() - 24, s10.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    public static void showprzydatne(final Player p) {
        final User user = UserManager.getUser(p);
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 45, ChatUtil.fixColor("&4&lDZIAL PRZYDATNE"));
        final ItemBuilder s1 = new ItemBuilder(Material.STRING, 1).setTitle(ChatUtil.fixColor("&4&lNICI")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6200 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c8")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s2 = new ItemBuilder(Material.ICE, 1).setTitle(ChatUtil.fixColor("&4&lLOD")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s3 = new ItemBuilder(Material.WATER_BUCKET, 10).setTitle(ChatUtil.fixColor("&4&lWIADRO WODY")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &650 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c1")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder s4 = new ItemBuilder(Material.SNOWBALL).setTitle(ChatUtil.fixColor("&4&lSNIEZKA")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &6100 coinsow")).addLore(ChatUtil.fixColor("&8� &7Ilosc: &c16")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic go kupic"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 35, s1.build());
        inv.setItem(inv.getSize() - 34, s3.build());
        inv.setItem(inv.getSize() - 33, s4.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    
    public static void show3(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 27, ChatUtil.fixColor("&4&lSklep Boosty"));
        final ItemBuilder gitemy = new ItemBuilder(Material.WRITTEN_BOOK).setTitle(ChatUtil.fixColor("&4&lZakladanie gildii za polowe ceny")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &610.000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder boosty = new ItemBuilder(Material.WRITTEN_BOOK).setTitle(ChatUtil.fixColor("&4&lWiekszy drop &8(&f1.25&8)")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt&8: &615.000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        final ItemBuilder disco = new ItemBuilder(Material.WRITTEN_BOOK).setTitle(ChatUtil.fixColor("&4&lDostep do komendy WB")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt&8: &65000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder repair = new ItemBuilder(Material.WRITTEN_BOOK).setTitle(ChatUtil.fixColor("&4&lDostep do komendy Repair")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt&8: &620.000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder ec = new ItemBuilder(Material.WRITTEN_BOOK).setTitle(ChatUtil.fixColor("&4&lDostep do komendy EC")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt&8: &620.000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder i4 = new ItemBuilder(Material.WRITTEN_BOOK).setTitle(ChatUtil.fixColor("&4&lTurbo Drop &8(&f15 min&8)")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt&8: &65000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder i5 = new ItemBuilder(Material.WRITTEN_BOOK).setTitle(ChatUtil.fixColor("&4&lTurbo Exp &8(&f15 min&8)")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt&8: &62500 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        inv.setItem(inv.getSize() - 27, gitemy.build());
        inv.setItem(inv.getSize() - 26, boosty.build());
        inv.setItem(inv.getSize() - 25, disco.build());
        inv.setItem(inv.getSize() - 24, repair.build());
        inv.setItem(inv.getSize() - 23, ec.build());
        inv.setItem(inv.getSize() - 22, i4.build());
        inv.setItem(inv.getSize() - 21, i5.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
    
    public static void show4(final Player p) {
        final Inventory inv = Bukkit.createInventory((InventoryHolder)p, 27, ChatUtil.fixColor("&4&lSklep Gildia"));
        final ItemBuilder soj = new ItemBuilder(Material.BOOK).setTitle(ChatUtil.fixColor("&4&lPowieksz liczbe sojuszy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &63000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder hp = new ItemBuilder(Material.BOOK).setTitle(ChatUtil.fixColor("&4&lOdnow hp gildii")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &63000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder efekt = new ItemBuilder(Material.BOOK).setTitle(ChatUtil.fixColor("&4&lLosowy efekt")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Koszt: &63000 coinsow")).addLore(ChatUtil.fixColor(" ")).addLore(ChatUtil.fixColor("&8� &eKliknij na przedmiot, aby kupic boosta"));
        final ItemBuilder wroc = new ItemBuilder(Material.BARRIER).setTitle(ChatUtil.fixColor("&cWroc do poprzedniej strony"));
        inv.setItem(inv.getSize() - 27, soj.build());
        inv.setItem(inv.getSize() - 26, hp.build());
        inv.setItem(inv.getSize() - 25, efekt.build());
        inv.setItem(inv.getSize() - 1, wroc.build());
        p.openInventory(inv);
    }
}
