// 
// Decompiled by Procyon v0.5.30
// 

package pl.virtual.api.utils;

import java.util.ArrayList;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import java.util.List;

public class PaczuszkaUtil
{
    public static ItemBuilder drop;
    public static List<ItemStack> drops;
    public static ItemBuilder dropiron;
    public static List<ItemStack> dropsiron;
    
    static {
        PaczuszkaUtil.drop = new ItemBuilder(Material.ENDER_CHEST).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8» &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8» &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &9&lCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8» &9nomenhc.eu")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor(""));
        (PaczuszkaUtil.drops = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        (PaczuszkaUtil.drops = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.drops = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        (PaczuszkaUtil.drops = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.drops = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.drops = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.drops = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 16).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8» &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 16).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8» &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 16).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8» &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 8).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 8).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 8).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 4));
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.drops.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.drops.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.WITHER_SKELETON_SKULL, 1).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 6).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());

    }
    
    static {
        PaczuszkaUtil.dropiron = new ItemBuilder(Material.ENDER_CHEST).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor(""));
        (PaczuszkaUtil.dropsiron = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 4).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 8));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        (PaczuszkaUtil.dropsiron = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.dropsiron = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        (PaczuszkaUtil.dropsiron = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.dropsiron = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.dropsiron = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        (PaczuszkaUtil.dropsiron = new ArrayList<ItemStack>()).add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 5).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 16).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 16).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 16).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 8).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 8).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.MOSSY_STONE_BRICKS, 8).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &f&lMarmur &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to magiczna skala")).addLore(ChatUtil.fixColor("&8� &7Ktora skrywa w sobie cenne itemy")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM             ")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.drops.add(new ItemBuilder(Material.ENDER_CHEST, 2).setTitle(ChatUtil.fixColor("&7&k:&f&k:&7&k:&6&l&l &9&lCase &7&k:&f&k:&7&k:&6&l&l")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Jest to jeden z cenniejszych")).addLore(ChatUtil.fixColor("&8� &7Przedmiotow ktore mozna zdobyc w grze")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &7Przedmioty jakie mozesz zdobyc")).addLore(ChatUtil.fixColor("&8� &7Z magicznej skrzynki znajdziesz pod &8&l/Drop")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&8� &8&lDarkCase &7zakupisz na")).addLore(ChatUtil.fixColor("&8� &7darkhard.pl")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("             &f&lAby otworzyc, kliknij PPM")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.PAPER, 1).addEnchantment(Enchantment.DURABILITY, 10).setTitle(ChatUtil.fixColor("&4&lVOUCHER NA TURBODROP 15m")).addLore(ChatUtil.fixColor("")).addLore(ChatUtil.fixColor("&7Kliknij aby otrzymac boosta")).addLore(ChatUtil.fixColor("")).build());
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.DIAMOND_BLOCK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.KNOCKBACK, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_SWORD).addEnchantment(Enchantment.DAMAGE_ALL, 3).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.FIRE_ASPECT, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 2));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 4));
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_BOOTS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_HELMET).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_LEGGINGS).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.IRON_CHESTPLATE).addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).addEnchantment(Enchantment.DURABILITY, 2).build());
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.GOLDEN_APPLE, 32));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.ENDER_PEARL, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.SLIME_BLOCK, 4));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemStack(Material.STICK, 16));
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.WITHER_SKELETON_SKULL, 1).build());
        PaczuszkaUtil.dropsiron.add(new ItemBuilder(Material.DIAMOND_PICKAXE).addEnchantment(Enchantment.DIG_SPEED, 6).addEnchantment(Enchantment.DURABILITY, 3).addEnchantment(Enchantment.LOOT_BONUS_BLOCKS, 3).build());

    }
}
